@ECHO OFF
echo Deleting old Hugo build...
rmdir docs /s
mkdir docs
echo charliehart.dev > docs/CNAME
echo Building Hugo site...
hugo
echo Committing to repo...
git add docs
git commit
echo Pushing to repo...
git push
